### PR TITLE
Cuckoo

### PR DESCRIPTION
**Pull request by kevthehermit**
Starts to extend Cuckoo Module.

Status - Displays basic Cuckoo Status
Add File - warns if analysis already exists and allows to resubmit. 
Get Dropped Files - Store any dropped files in Viper and set Parent attribute.

This also adds support for the Accuvent Cuckoo-Modified Fork.

ToDo: Extend Submission Options.

### CODE REVIEW

**Comment by botherder** [comment]
Is this built on top of Cuckoo 2.0-dev or the stable?

**Comment by kevthehermit** [comment]
tested with 

cuckoo 2.0-dev and 1.3-Optiv from brads fork.

Will pull Cuckoo Stable tonight and test / adjust

**Comment by kevthehermit** [comment]
Tested with Stable Version 1.2 no changes required.

**Comment by botherder** [comment]
If everything with 2.0 works, I'm fine with it.

**Pull request merged**
