### PR TITLE
Fixing pehash module

### PR DESCRIPTION
**Pull request by kryptpt**
Fixing #217 issue

### CODE REVIEW

**Comment by botherder** [comment]
Can someone please review this? Possibly @nheijmans that created the module or @jahrome?

**Comment by nheijmans** [comment]
Yes I build the module. I was not aware something was not working anymore. 

I will look at it tomorrow! Thank you for informing me.

**Comment by kryptpt** [comment]
@nheijmans You should read the gist first to understand the pehash problem. https://gist.github.com/wxsBSD/07a5709fdcb59d346e9e

**Comment by nheijmans** [comment]
Hi Emanuel,

I have read the gist mentioned in your previous e-mail. It gave some interesting insights on the implementation of the PE hash. Unfortunately
i don’t have enough knowledge to help with this right now, but I will do some research and more reading and try to get an answer as well on the subject.

Kind regards,

N

**Comment by kryptpt** [comment]
@nheijmans Probably it's better waiting for some answers about the article. You can close the PR if you want.

**Comment by botherder** [comment]
I'm keen on having this fixed if there is in fact an implementation flaw, but as this probably require some deeper analysis and review, we should probably postpone to 1.3.

**Comment by kryptpt** [comment]
You will spot a few bugs (slice notation misunderstanding) if you read the article. But there are a lot of questions to be made to the author's article before to suggest any correction. I think it's better don't change anything if it generates consistent signatures with others platforms/communities. It's fine if you decide in closing the PR.

**Comment by nheijmans** [comment]
I agree with Emanuel. Plus i’m using the PE Hash for 3-4 months now on a project and it is linking malware samples successfully (for now). Let’s keep a close eye on it and if an update is given we can take action based on that.

**Comment by AnyMaster** [comment]
please look gist  [comment](https://gist.github.com/wxsBSD/07a5709fdcb59d346e9e)

**Comment by nheijmans** [comment]
Hi AnyMaster,

Thank you for sharing your work! I will look at your implementation and run some tests. If everything goes well i’ll replace the current Viper pehash module with yours. 

Regards

**Comment by kevthehermit** [comment]
Ok so the implementation is definatly off. 

Checking against https://totalhash.cymru.com/blog/pehash-source-code/ And some random samples our pe hashes do not match those on totalhash. 

This pull request also fails. 

```
Traceback (most recent call last):
  File "/root/github/viper/viper/core/ui/console.py", line 266, in start
    module.run()
  File "/root/github/viper/modules/pe.py", line 955, in run
    self.pehash()
  File "/root/github/viper/modules/pe.py", line 879, in pehash
    current_pehash = calculate_pehash(__sessions__.current.file.path)
  File "/root/github/viper/modules/pehash/pehasher.py", line 41, in calculate_pehash
    #pad to 16 bits
  File "/usr/local/lib/python2.7/dist-packages/bitstring.py", line 1130, in __xor__
    raise ValueError("Bitstrings must have the same length "
ValueError: Bitstrings must have the same length for ^ operator.

```

Closing and creating a new pull to make our hashes match totalhash.

**Pull request closed without merging**
