### PR TITLE
Plenty of updates

### PR DESCRIPTION
**Pull request by Rafiot**
Summary of the changes:

* Open an event whenever possible
* New publish method
* New version method (to check if the system is up-to-date)
* Better error handling
* Possible to disable SSL verification for self signed cert
* Cleanup

### CODE REVIEW

**Comment by Rafiot** [comment]
Note that it requires MISP HEAD to work

**Comment by kevthehermit** [comment]
Is there anyway to check MISP version and warn that MISP or PyMISP needs updating if they are not at the min required version? 

Also can we add a publish option?

**Comment by Rafiot** [comment]
Good point, we need to have a way to fetch the API version from the running instance, and get the newest version available from github => https://github.com/MISP/MISP/blob/master/VERSION.json

Right now, I don't think it is possible (I'm opening an issue to make sure).

Either way, this change will not crash if the id is not present in the response so it's not a problem.

**Comment by Rafiot** [comment]
Publish? you mean to publish the event? if yes, totally, I need to update PyMISP for that.

I completely forgot about it. Will do it later today.

**Comment by kevthehermit** [comment]
Yes publish an event :) I have been doing this on new events with 

```
event = misp.new_event(distrib, threat, analysis, info, published=True)
```

**Comment by Rafiot** [comment]
Yeah, but it should be an clean option, in the module :)

**Comment by Rafiot** [comment]
No need to merge, I will add a method to check the version of MISP later today and update PyMISP again.

**Comment by Rafiot** [comment]
Fixed -> https://github.com/viper-framework/viper/issues/355

And plenty of cleanup and improvement in the code.

**Comment by kevthehermit** [comment]
Love the new version check :)

although sometimes i get versions printed out more than once. Other times just once.
```
viper > misp --url http://misp.malwareconfig.com -k u..........J5 version
[*] The version of your MISP API is: 1.12
[*] The version of MISP API master branch is: 1.12
[*] The version of your MISP API is: 1.12
[*] The version of MISP API master branch is: 1.12
[*] The version of your MISP API is: 1.12
[*] The version of MISP API master branch is: 1.12
[*] The version of your MISP API is: 1.12
[*] The version of MISP API master branch is: 1.12
[*] The version of your MISP instance is: 2.3.130
[*] The version of MISP master branch is: 2.3.130
[+] Congratulation, your MISP instance is up-to-date
[+] Congratulation, the MISP API installed is up-to-date
viper > misp --url http://misp.malwareconfig.com -k u.........J5 version
[*] The version of your MISP API is: 1.12
[*] The version of MISP API master branch is: 1.12
[*] The version of your MISP instance is: 2.3.130
[*] The version of MISP master branch is: 2.3.130
[+] Congratulation, your MISP instance is up-to-date
[+] Congratulation, the MISP API installed is up-to-date
viper >


```

URL checking needs some error handling

If i miss the http:// off

```
viper > misp --url misp.malwareconfig.com -k u........J5 version
[!] The command misp raised an exception:
Traceback (most recent call last):
  File "/root/github/viper/viper/core/ui/console.py", line 270, in start
    module.run()
  File "/root/github/viper/modules/misp.py", line 703, in run
    self.version()
  File "/root/github/viper/modules/misp.py", line 618, in version
    misp_version = self.misp.get_version()
  File "build/bdist.linux-x86_64/egg/pymisp/api.py", line 656, in get_version
    return session.get(url).json()
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 467, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 421, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 359, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 287, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 338, in prepare_url
    "Perhaps you meant http://{0}?".format(url))
MissingSchema: Invalid URL u'servers/getVersion': No schema supplied. Perhaps you meant http://servers/getVersion?
viper >

```

If i give a url to something that isnt misp

```
viper > misp --url http://malwareconfig.com -k u.........J5 version
[!] The command misp raised an exception:
Traceback (most recent call last):
  File "/root/github/viper/viper/core/ui/console.py", line 270, in start
    module.run()
  File "/root/github/viper/modules/misp.py", line 703, in run
    self.version()
  File "/root/github/viper/modules/misp.py", line 618, in version
    misp_version = self.misp.get_version()
  File "build/bdist.linux-x86_64/egg/pymisp/api.py", line 656, in get_version
    return session.get(url).json()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 2 column 1 (char 1)
viper >

```

**Comment by Rafiot** [comment]
1. version check: how is that even possible ?! I'll try to reproduce later today...
2. Good point. This module really needs a generic way to handle errors. Same, I'll look at it later on today,

**Comment by Rafiot** [comment]
I cannot manage to reproduce the issue with the version... There are no loops anywhere, it doesn't make any sense.

**Comment by Rafiot** [comment]
Issues with invalid URL are now fixed (use pymisp 2.0).

**Comment by kevthehermit** [comment]
Am in Italy till Friday. Will see if i can reproduce on a clean install when i get back

**Comment by Rafiot** [comment]
No hurry. Also, I'm going to improve the error handling at PyMISP level so it's going to be more consistent in the viper module.

**Comment by Rafiot** [comment]
I may have broken everything, but now the error handling is much saner and you can rely on PyMISP to produce a standardized output.

**Comment by Rafiot** [comment]
\o/ thank you :)

**Pull request merged**
