### PR TITLE
Added the ability to upload password protected zip files with the API

### PR DESCRIPTION
**Pull request by Lost4Now**
I added the ability to upload a zip file through the use of api.py.  By setting setting header values, the zip will be extracted and each file located in the script will be uploaded.  All the real logic is copied from web.py and a few imports and methods were added to support the processing of the zip file.  If this gets accepted I will add the processing of the other archive types.

headers={'compression': 'ZIP', 'compression_password': 'infected'}

### CODE REVIEW

**Comment by Lost4Now** [comment]
Are you talking about modifying the docs/source/usage/web.rst file?  If so I can take a stab at updating it if you like.  This is only the second time I have contributed to a open source project and first time for dealing with the docs.

**Comment by kevthehermit** [comment]
I would hold off, Im re writing the web interface and API in django at the moment. 

You can see my draft work here - https://github.com/kevthehermit/ViperV2/tree/master/web

**Comment by Lost4Now** [comment]
Interesting.  I look forward to playing with the Django application.  Have you thought about using jquery on the interface to make it appear a little more dynamic?  For example do I need to show the zip password box before a compression scheme is selected.  I would be willing to help out any way I can.

**Comment by 2sec4u** [comment]
It'd be great if this could get merged in, I think development on the other web interface halted.

**Comment by Rafiot** [comment]
I wouldn't mind merging it, but there is a conflict. @2sec4u: are you using it? Do you mind fixing the conflict so I can merge it?

**Comment by Lost4Now** [comment]
I can make a pull of the recent version, and add the changes.  This was done some time ago, so a lot has changed.

**Comment by Rafiot** [comment]
Definitely, I try to cleanup the backlog. If you do a new PR, or update this one, I'll merge it.

**Comment by 2sec4u** [comment]
@Rafiot Not using it currently. Apologies.

**Comment by Lost4Now** [comment]
I have submitted a new pull request.  The request ID is #499.

**Comment by Rafiot** [comment]
Other PR merged.

**Pull request closed without merging**
