### PR TITLE
implement Archiver class to handle (un)zipping of archives

### PR DESCRIPTION
**Pull request by frennkie**
The (django) branch of the web interface has some code for decompressing an uploaded file. In my opinion it makes sense to have a backend functionality than handles compressing and extracting files. This PR adds an "Archiver" class to core and I would like to get some feedback whether others think that this makes sense too.

This PR now also adds an option to **export** to a 7z compressed archive (which can *optionally* be password protected).

```
viper cmd.exe > export -h
usage: export [-h] [-z] [-7] [-p] value

Export the current session to file or zip

positional arguments:
  value           path or archive name

optional arguments:
  -h, --help      show this help message and exit
  -z, --zip       Export session in a zip archive (PW support: No)
  -7, --sevenzip  Export session in a 7z archive (PW support: Yes)
  -p, --password  Protect archive with a password (PW) if supported
```

If this is accepted it would be pretty straightforward to add password support when adding (store/upload) files (see #474). Extracting with password to zip (#105) could also easily be added as a new Extractor sub class.

Open tasks are:
* [x] adding password support when compressing (#474)
* [x] adding password support on more extraction types (see also #105)
* [x] adding more extraction types (e.g. 7z (#342),  rar...)

### CODE REVIEW

**Comment by Rafiot** [comment]
FYI, I like it :)

**Comment by frennkie** [comment]
Good to hear that.. I'm making good progress.. coverage currently at 94%... ;-)
I added password support when compressing to .7z + when extracting .zip, .rar and .7z and for the start there are already the most important Extractors available.. so I'll check of the three tasks..

**Comment by Rafiot** [comment]
hmm?

**Comment by frennkie** [comment]
> hmm?

weird.. I may have accidentally pressed close when browsing this PR from my mobile m)

**Comment by Rafiot** [comment]
heh, ok, I was confused ;)

**Comment by Rafiot** [comment]
Should I merge it?

**Comment by frennkie** [comment]
There is not a lot that could break as most of the PR is the new file.. but it would be great if you could review (and test?!) the changes in commands.py.

**Comment by Rafiot** [comment]
sure, I'll do that before merging :)

**Comment by Rafiot** [comment]
Works for me!

**Pull request merged**
