### PR TITLE
[OUT] Improve table printing

### PR DESCRIPTION
**Pull request by Rafiot**
When one of the entry in the table is too long, it breaks the rendering. This commit will cut the too long lines.

### CODE REVIEW

**Comment by Rafiot** [comment]
Woops, it fails if the array contains an integer...

**Comment by Rafiot** [comment]
This pull request is working very reliably for me, would be cool to merge it :)

**Comment by kevthehermit** [comment]
Can you add an error handling line in there for the new import. If you dont manually install terminaltables

```
localadmin@tech-viper:~/viper$ ./viper.py
Traceback (most recent call last):
  File "./viper.py", line 8, in <module>
    from viper.core.ui import console
  File "/home/localadmin/viper/viper/core/ui/console.py", line 11, in <module>
    from viper.common.out import *
  File "/home/localadmin/viper/viper/common/out.py", line 5, in <module>
    from terminaltables import AsciiTable
ImportError: No module named terminaltables
localadmin@tech-viper:~/viper$
```

**Comment by kevthehermit** [comment]
Also have this error

```
You have 9690 files in your default repository
viper > find all
[!] The command find raised an exception:
Traceback (most recent call last):
  File "/home/localadmin/viper/viper/core/ui/console.py", line 228, in start
    print_output(self.cmd.output, filename)
  File "/home/localadmin/viper/viper/common/out.py", line 89, in print_output
    rows=entry['data']['rows']
  File "/home/localadmin/viper/viper/common/out.py", line 42, in table
    temp += '\n'.join(textwrap.wrap(l, max_length_col)) + '\n'
  File "/usr/lib/python2.7/textwrap.py", line 354, in wrap
    return w.wrap(text)
  File "/usr/lib/python2.7/textwrap.py", line 329, in wrap
    return self._wrap_chunks(chunks)
  File "/usr/lib/python2.7/textwrap.py", line 258, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width -106 (must be > 0)
viper >

```

**Comment by Rafiot** [comment]
oh, sorry for that, fixing...

**Comment by kevthehermit** [comment]
Tested, works nicly can you update the merge conflict and i will merge as soon as its done. thanks

**Comment by Rafiot** [comment]
Done :)

**Pull request merged**
