### PR TITLE
Added new command to parse out dll names under the pe command.

### PR DESCRIPTION
**Pull request by xorhex**
Tried to copy the style as best I could.  Let me know of any deviations, and I'll correct and re-submit.

### CODE REVIEW

**Comment by botherder** [comment]
I might be missing somethings, but isn't this a duplicate of the pe exports command?

**Comment by xorhex** [comment]
Wasn't able to duplicate the functionality when using the `pe exports command` but I'm no viper expert.

If the file is a dll, it pulls out the name of the dll itself, not the dll exports names.

`return "{0}".format(pe.DIRECTORY_ENTRY_EXPORT.name)`

**Comment by botherder** [comment]
Oh I see. I just skimmed at the commit too quickly.

**Comment by botherder** [comment]
Thanks.

**Pull request merged**
