### PR TITLE
Update VT module (use external lib)

### PR DESCRIPTION
**Pull request by Rafiot**
I didn't try all the options, but I'll do it later today or tomorrow, but if you want to try in the mean time, please do.

### CODE REVIEW

**Comment by Rafiot** [comment]
(do not merge immediately, I'm working on the MISP integration... :) )

**Comment by Rafiot** [comment]
Done. This last commit probably needs some more love, but if you can, please give a try.

**Comment by Rafiot** [comment]
What do you think of the "misp flag" ? I'm planning to implement a similar function to other modules.

**Comment by botherder** [comment]
I'm generally happy with supporting MISP, as long as it doesn't become too pervasive and adds too much complexity for future maintenance of all modules.

**Comment by Rafiot** [comment]
I'll try to make it as lightweight as possible, the code I'll commit later today will be cleaner.

**Comment by Rafiot** [comment]
I'd consider this pull request done. If you could give a try & merge if everything is fine, that would be great :)

**Comment by Rafiot** [comment]
I use the fork of the VT api on my account, because the official version doesn't work when trying to upload a sample.

**Comment by Rafiot** [comment]
I found a but in `misp check_hashes`, I'll fix it later today.

**Comment by Rafiot** [comment]
I still do updates when I find improvements, but if you can merge the pull request, that would be great. :)

**Comment by kevthehermit** [comment]
Merge conflict in requirements.txt

before i install the new library i was getting this error

```
viper > virustotal
[!] The command virustotal raised an exception:
Traceback (most recent call last):
  File "/home/localadmin/viper_testing/update_vt/viper/core/ui/console.py", line 233, in start
    module = __modules__[root]['obj']()
  File "/home/localadmin/viper_testing/update_vt/modules/virustotal.py", line 39, in __init__
    self.vt = vt(cfg.virustotal.virustotal_key)
NameError: global name 'vt' is not defined
viper > exit

```

Search, domains, ips all working nicely. 

Download is not working for me

```
viper > virustotal --search 437ea3b450fd1043b20553996c8e9e00
[*] 43 out of 56 antivirus detected 437ea3b450fd1043b20553996c8e9e00 as malicious.
[*] https://www.virustotal.com/file/b21a5ac48502ff75057f9773bf31abd970ef6c75a2c0ea1c871dd4e81ec5a994/analysis/1445922956/

viper > virustotal -d 437ea3b450fd1043b20553996c8e9e00
[!] unrecognized arguments: 437ea3b450fd1043b20553996c8e9e00

viper >

```

Submit fix has been merged in to the the authors Git but not update on pip. I have asked him to update pip - https://github.com/blacktop/virustotal-api/issues/6 

In the mean time the requirements.txt could point to the git path rather than pip.

**Comment by Rafiot** [comment]
The issue with download is because the download option is a bit unclear: you have to do 
`virustotal --search 437ea3b450fd1043b20553996c8e9e00 -d `

I can improve it if you like but not this weekend ;)

**Comment by Rafiot** [comment]
Updated requirement, fix lib check

**Comment by kevthehermit** [comment]
Still showing as a merge conflict

**Comment by Rafiot** [comment]
No idea what happened, fixed now.

**Comment by Rafiot** [comment]
Can you merge it, please? :)

**Comment by Rafiot** [comment]
Thanks!

**Pull request merged**
