### PR TITLE
[WIP] Refactoring and port to python3, Initial test cases

### PR DESCRIPTION
**Pull request by Rafiot**
Also, it removes a vast majorities of the bundled-in dependencies (and needs a LOTS of testing, because that's going to break stuff).

To fix:
- [X] pe imphash (if you use HEAD)
- [x] pe peid
- [x] pe language

Dependencies status
- [x] pymacho is broken, and doesn't work (python 2 & 3) on the samples I have.
- [ ] pype32 has no python3 support but is only used in 3 rat submodules.
- [x] peepdf is beyond my sanity: this beast is > 16k lines of code + dependencies, I won't port it. The good news is that it is only used to extract streams out of PDFs, and pdf-parser does that too, is py3 compatible and sane.
- [x] ~~androguard with https://github.com/appknox/androguard~~ works with https://github.com/androguard/androguard

### CODE REVIEW

**Comment by Rafiot** [comment]
@botherder @deralexxx do you mind giving a try to this branch, and tell me what is broken for you? 
I tested most of the modules and they are all updated except the Mach-O one that is most probably broken: I don't have samples for it but the code look very sane, so I guess it will mostly be a bunch of issues related to bytes vs string but that will be straight forward to fix.

pype32 is an other problem, and I don't really see how to fix it.

**Comment by Rafiot** [comment]
I fixed the imports or Mach-0, but the lib doesn't work at all (python2 & 3) on the samples I have.

**Comment by frennkie** [comment]
Hey Rafiot,

just want to confirm that I'm on the right track here to start testing your changes in this py3 branch.

Here's what I did, what I encountered and how I tried to ignore / "workaround" the errors:

## install dependencies/tools from OS

```
sudo -H apt-get update
sudo -H apt-get install -y gcc python3-dev python3-pip python3-yara
sudo -H apt-get install -y build-essential libssl-dev libffi-dev   
```

```
wget http://sourceforge.net/projects/ssdeep/files/ssdeep-2.13/ssdeep-2.13.tar.gz/download -O /tmp/ssdeep-2.13.tar.gz
cd /tmp
tar -zxvf ssdeep-2.13.tar.gz
cd ssdeep-2.13
./configure && make
sudo make install
sudo pip3 install pydeep
```

## clone git repo and switch to py3 branch

```
cd ~/work/
git clone https://github.com/Rafiot/viper
cd viper
git co py3
```

### edit requirements.txt

```
vi requirements-dev.txt (remove/comment out line 11 and 12 - olefile, oletools)
```

### install requirements

```
sudo -H pip3 install -r requirements-dev.txt
```

## run Viper

```
python3 viper-cli
```


## Running Viper with Python3 - "Something wrong..."

```
[20:13:12 - user at ubuntu144.home.example.com in ~/work/viper (py3|✚1)]
$: git diff
diff --git a/requirements-dev.txt b/requirements-dev.txt
index 021bdc3..3e1c5cb 100644
--- a/requirements-dev.txt
+++ b/requirements-dev.txt
@@ -8,8 +8,8 @@ dnspython
 enum34
 idna
 ipaddress
-olefile
-oletools
+#olefile
+#oletools
 pbkdf2
 pyasn1
 pycparser
[20:13:14 - user at ubuntu144.home.example.com in ~/work/viper (py3|✚1)]
$: python3 viper-cli
[!] Something wrong happened while importing the module viper.modules.pdf: No module named 'viper.modules.pdftools.pdfid'
[!] Something wrong happened while importing the module viper.modules.rats.hawkeye: No module named 'datadirs'
[!] Something wrong happened while importing the module viper.modules.rats.njrat: No module named 'datadirs'
[!] Something wrong happened while importing the module viper.modules.rats.predatorpain: No module named 'datadirs'
         _
        (_)
   _   _ _ ____  _____  ____
  | | | | |  _ \| ___ |/ ___)
   \ V /| | |_| | ____| |
    \_/ |_|  __/|_____)_| v1.3-dev
          |_|

You have 0 files in your default repository
viper > store -f /home/user/work/files/
[+] Stored file "cmd.exe" to /home/user/.viper/binaries/d/b/0/6/db06c3534964e3fc79d2763144ba53742d7fa250ca336f4a0fe724b75aaff386
[*] Session opened on /home/user/.viper/binaries/d/b/0/6/db06c3534964e3fc79d2763144ba53742d7fa250ca336f4a0fe724b75aaff386
[*] Running command "yara scan -t"
[*] Scanning cmd.exe (db06c3534964e3fc79d2763144ba53742d7fa250ca336f4a0fe724b75aaff386)
[*] Running command "triage"
[+] Stored file "whoami.exe" to /home/user/.viper/binaries/c/3/6/c/c36cf78f2257f606ab67b14afb02dca652a3fa6907c7805efbd2d47241ee609a
[*] Session opened on /home/user/.viper/binaries/c/3/6/c/c36cf78f2257f606ab67b14afb02dca652a3fa6907c7805efbd2d47241ee609a
[*] Running command "yara scan -t"
[*] Scanning whoami.exe (c36cf78f2257f606ab67b14afb02dca652a3fa6907c7805efbd2d47241ee609a)
[*] Running command "triage"
viper > find all
+---+------------+-----------------------+----------------------------------+------+
| # | Name       | Mime                  | MD5                              | Tags |
+---+------------+-----------------------+----------------------------------+------+
| 1 | cmd.exe    | application/x-dosexec | 5746bd7e255dd6a8afa06f7c42c1ba41 |      |
| 2 | whoami.exe | application/x-dosexec | ec2231c0fea6b821a5ed097419744205 |      |
+---+------------+-----------------------+----------------------------------+------+
viper > open -l 1
[*] Session opened on /home/user/.viper/binaries/1/7/f/7/17f746d82695fa9b35493b41859d39d786d32b23a9d2e00f4011dec7a02402ae
viper cmd.exe > info
+----------+----------------------------------------------------------------------------------------------------------------------------------+
| Key      | Value                                                                                                                            |
+----------+----------------------------------------------------------------------------------------------------------------------------------+
| Name     | cmd.exe                                                                                                                          |
| Tags     |                                                                                                                                  |
| Path     | /home/user/.viper/binaries/d/b/0/6/db06c3534964e3fc79d2763144ba53742d7fa250ca336f4a0fe724b75aaff386                            |
| Size     | 345088                                                                                                                           |
| Type     | PE32+ executable (console) x86-64, for MS Windows                                                                                |
| Mime     | application/x-dosexec                                                                                                            |
| MD5      | 5746bd7e255dd6a8afa06f7c42c1ba41                                                                                                 |
| SHA1     | 0f3c4ff28f354aede202d54e9d1c5529a3bf87d8                                                                                         |
| SHA256   | db06c3534964e3fc79d2763144ba53742d7fa250ca336f4a0fe724b75aaff386                                                                 |
| SHA512   | 3a968356d7b94cc014f78ca37a3c03f354c3970c9e027ed4ccb8e59f0f9f2a32bfa22e7d6b127d44631d715ea41bf8ace91f0b4d69d1714d55552b064ffeb69e |
| SSdeep   |                                                                                                                                  |
| CRC32    | D51795E3                                                                                                                         |
| Parent   |                                                                                                                                  |
| Children |                                                                                                                                  |
+----------+----------------------------------------------------------------------------------------------------------------------------------+
viper cmd.exe >
```

Is all this expected behaviour from your perspective?!

**Comment by Rafiot** [comment]
Few remarks: 
* Why removing olefile and oletools?
* PDFid is now a submodule, and need to be initialized this way:
```
git submodule init
git submodule update
```
* The 3 RAT modules are failing because pype32 isn't python3 compatible and it seems to be a monster to port

Besides that, it seems everything is working as expected.

**Comment by botherder** [comment]
I think they were probably commented at some point cause they broke something. I'm not sure.

**Comment by frennkie** [comment]
> Why removing olefile and oletools?

@Rafiot: pip3 install is complaining that the requirement for those is listed twice:
* https://github.com/Rafiot/viper/blob/py3/requirements-dev.txt#L11
* https://github.com/Rafiot/viper/blob/py3/requirements-dev.txt#L12

and 

* https://github.com/Rafiot/viper/blob/py3/requirements-dev.txt#L47
* https://github.com/Rafiot/viper/blob/py3/requirements-dev.txt#L48

**Comment by Rafiot** [comment]
woops, right, thanks :)

**Comment by frennkie** [comment]
@Rafiot what do you think of linting, unittests and possible even some (basic) integration tests..? A switch to supporting Python3 might be a good moment to introduce these... ;-D

Running `flake8 --max-line-length=120 --exclude viper/modules` actually only produces 118 violations which sounds manageable. When Including the modules the numbers goes up to 1,5k :-(

**Comment by frennkie** [comment]
Running `py3kwarn viper | grep -v "FixInput"` lists 34 lines that also need to be checked. 

I did not find a way to eliminate the "FixInput" warnings, but due to this code you included I'm pretty sure they can be ignored: 
```
try:
    input = raw_input
except NameError:
    pass
```

**Comment by frennkie** [comment]
I don't have a lot of experience with six but as it's main purpose is to provide combatibility with py2 and py3 I started fixing py3warning with it. @Rafiot what do you think about this: https://github.com/frennkie/viper/commit/22902343112de1e53e9cbb6b9b0723f4e6e42366

**Comment by Rafiot** [comment]
1. https://github.com/frennkie/viper/tree/py3 <= looks good to me, should I do a PR and merge in this branch? 
Let's wait for the modules, it will be a mess.

2. The raw input thing, yes, let's keep it like that as long as we support python2.7.
3. `six.text_type` sure, I generally do stuff like that (but I prefer the six approach):

```
try:
    # Python2
    basestring
    unicode
except NameError:
    basestring = str
    unicode = str

```

**Comment by frennkie** [comment]
> looks good to me, should I do a PR and merge in this branch?

Well.. "I'm only getting started" .. no, seriously.. I wanted to know whether that's the right direction to go. I'll be able to spent some more time on it on the weekends and after work.. but how much time that is usually varies a lot.

I think I'll sent a PR right now for the changes in the py3 branch. I'm currently working on the Django Web/API stuff which is fun but a huge amount of work.. ;-) 

So I'll continue looking in the py3 stuff sometime next week.

**Comment by Rafiot** [comment]
the changes you made in the py3 branch are clean and don't change anything critical, merging it now will make my life easier when I review later :)

**Comment by egberts** [comment]
Apparently, Rafiot's py3 has since evolved better (at this point) than the viper-foundation's current py3 branch, for it had fixed the SyntaxError for invalid syntax of multiple Exception labels on 'except' statements.

**Comment by egberts** [comment]
During the 'notes -v 1' command, it failed with:
    TypeError: Can't convert 'bytes' object to str implicitly TypeErrorI've had to modify the viper/core/ui/commands.py, line 312 to surround both '\n' and 'note.body' with 'str()' so that it shows:

    self.log('info', bold('Body:') + str('\n') + str(note.body))

**Comment by frennkie** [comment]
> pe imphash (if you use HEAD)

@Rafiot I'm having issue with your [updated version](https://github.com/viper-framework/pefile/tree/master)  of pefile . For all the files I tested I get an error when loading the file:

```
pe = pefile.PE("files/cmd.exe")
[...]
/home/robbie/work/pefile/pefile.pyc in parse_directory_bound_imports(self, rva, size)
   2560             if name_str:
   2561                 invalid_chars = [
-> 2562                     c for c in bytearray(name_str) if
   2563                         chr(c) not in string.printable]
   2564                 if len(name_str) > 256 or invalid_chars:

TypeError: unicode argument without an encoding
```

**Comment by Rafiot** [comment]
@egberts good catch, working on it

@frennkie Ok, this is weird: works for me (pythonl2 and python3). Can you try to force the reinstallation? (`pip install -I -e .` from the directory)

**Comment by Rafiot** [comment]
@egberts your bug should be fixed (and I improved a bit the notes command while I was at it)

**Comment by frennkie** [comment]
> @frennkie Ok, this is weird: works for me (python2 and python3). Can you try to force the reinstallation? (pip install -I -e . from the directory)

I created a new environment from scratch and get the same results (both py2 and py3):

```

$: pip3 install -e git+https://github.com/viper-framework/pefile.git#egg=pefile
$: pip3 freeze | grep pefile
-e git+https://github.com/viper-framework/pefile.git@26c6b407d25df6a3b2487b968236d2df8146964f#egg=pefile

$: python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pefile
>>> pe =  pefile.PE("/home/user/work/files/cmd.exe")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/work/testing/python3/venv/src/pefile/pefile.py", line 1765, in __init__
    self.__parse__(name, data, fast_load)
  File "/home/user/work/testing/python3/venv/src/pefile/pefile.py", line 2122, in __parse__
    self.parse_data_directories()
  File "/home/user/work/testing/python3/venv/src/pefile/pefile.py", line 2459, in parse_data_directories
    value = entry[1](dir_entry.VirtualAddress, dir_entry.Size)
  File "/home/user/work/testing/python3/venv/src/pefile/pefile.py", line 2547, in parse_directory_bound_imports
    c for c in bytearray(name_str) if
TypeError: string argument without an encoding
>>>
```

**Comment by Rafiot** [comment]
Can you attach a file that fails, please? All the files I try are working so I don't understand what's going on.

What happen if you print name_str?

**Comment by frennkie** [comment]
Maybe my understanding is wrong.. I used e.g. "cmd.exe" and "whoami.exe" both shipped with my Windows 7 installation.. those are PE files..

**Comment by frennkie** [comment]
@Rafiot just tested two other random files and they are working.. so not sure what's wrong with cmd.exe and whoami.exe..

**Comment by frennkie** [comment]
Testing an .apk.  - I installed androguard:

```
$: pip freeze | grep ndro
-e git+https://github.com/appknox/androguard@b5572cbf6fa2be00b0d126b2d4968d68d6253f6f#egg=ak_androguard
```

But I get an import error on a [print statement](https://github.com/appknox/androguard/blob/v2-py3/androguard/core/bytecodes/dvm.py#L2402)

```
from androguard.core.bytecodes.dvm import *
  File "/home/user/work/androguard/androguard/core/bytecodes/dvm.py", line 2402
    print(nb, end=' ')
                 ^
SyntaxError: invalid syntax
````

**Comment by Rafiot** [comment]
Yeah, so androguard, I didn't test at all, except it seemed to install without exploding :) 
So maybe you want to start patching it... :p 

For pefile, I'm patching it as we speak, and probably breaking all compatibility with python2...

**Comment by frennkie** [comment]
> Yeah, so androguard

The [main repo](https://github.com/androguard/androguard) actually doesn't look too bad for py3 on first sight. When I remove `from androguard.core.analysis.ganalysis import *` from apk.py it does load. Although I still get an error on all commands:

```
viper app-release.apk > apk -i
[*] Processing the APK, this may take a moment...
[!] Error: 'NoneType' object has no attribute 'get_method_analysis'
```

**Comment by Rafiot** [comment]
Yeah, same as pefile, it is somewhat tested with python3, and then patched as it goes when we find a bug. I bet it is the same with androguard :) 

Feel free to start with a few small patches (no full pep8 refactoring), so you improve the python3 support, and do a PR on the main repo.

**Comment by frennkie** [comment]
@Rafiot Just a reminder: I manged to run the apk module on Python3 with androguard/androguard and **not** appknox/androguard.

**Comment by Rafiot** [comment]
@frennkie nice! changing the dependency then.

**Comment by frennkie** [comment]
The three rat modules that still use pype32 all have the same function:

```
# Get a list of strings from a section
def get_strings(pe, dir_type):
    counter = 0
    string_list = []
    m = pe.ntHeaders.optionalHeader.dataDirectory[14].info
    for s in m.netMetaDataStreams[dir_type].info:
        for offset, value in s.items():
            string_list.append(value)
        counter += 1
    return string_list
```

It seems to me that `pe.ntHeaders.optionalHeader.dataDirectory[14]` can be replaced with this `pe.OPTIONAL_HEADER.DATA_DIRECTORY[14]` from pefile. But I not familiar with this and don't have samples to test. And I also can't find anything in pefile that would replace `netMetaDataStreams[dir_type].info`... :-/

**Comment by Rafiot** [comment]
Yeah, I need to look that up and find a solution... But thanks for the hint regarding  `OPTIONAL_HEADER.DATA_DIRECTORY`

**Comment by Rafiot** [comment]
@frennkie: I fixed the test cases: __sessions__ is a global variable, we have to make sure it is properly closed between each tests -> https://github.com/viper-framework/viper/pull/495/commits/7d85e8f325b21a4a80b0f9dd5af15ce80a7b4c3d#diff-df6265635c048b268138ec9a3fbf2d03R19

**Comment by frennkie** [comment]
@Rafiot great! :-)

**Comment by frennkie** [comment]
The two Mach-O samples I found work with both Py2+Py3 (after merging viper-framework/Mach-O#1) - so I think we can check off pymacho too.. Any more things that are known not to work on Python3 (besides PE in the RATs)

**Comment by Rafiot** [comment]
I think it is mostly good now... I have a few more test cases in the pipes I'll merge over the weekend, but I think we are very close to merging.

@botherder @deralexxx: what do you think?

**Comment by frennkie** [comment]
Sounds excellent!

**Comment by deralexxx** [comment]
Man this is gold! IMO merge it, spent around an hour playing and testing how I usually work with it, but seems great.

Maybe we should aim to make viper 3.0 with respect to the main shift to python 3 very soon.

**Comment by Rafiot** [comment]
I did some merging and tox is now failing with `No such file or directory`, and I don't get where it comes from...

**Comment by frennkie** [comment]
@Rafiot I'll have a look at it tomorrow.. my first guess is that it's related to this settings https://github.com/viper-framework/viper/blob/master/tests/conftest.py#L16 as I had some issue with it too: 

But I found it pretty helpful for the tests to be able to have a clean working dir (`./`).

**Comment by frennkie** [comment]
If you comment out https://github.com/viper-framework/viper/blob/master/tests/conftest.py#L18 less tests fail. I think this is really strange behaviour of pytest. Somehow it is still trying the access the directory which it deleted in L18.

The reason why I added the `shutil.rmtree` is to avoid having my `/tmp` fill up with loads of test artifacts when manually running `pytest` (which is quicker than running the full suite) but in Travis/tox this can really be ignored..

**Comment by Rafiot** [comment]
:+1:

**Comment by frennkie** [comment]
Something broke in pefile. I have a sample and when I run pe security on it I get a traceback. I think the problem is the @ sign (hex a9) but have no clue how to properly fix this.

Using `-e git+https://github.com/viper-framework/pefile.git@c70c278e1e432726a7db35dac39bfc9264040ed7#egg=pefile
`
```
viper 513a6e4e94369c64cab49324cd49c44137d2b66967bb6d16394ab145a8e32c45 > pe security
[!] The command pe raised an exception:
Traceback (most recent call last):
  File "/home/user/work/viper/viper/core/ui/console.py", line 243, in start
    module.run()
  File "/home/user/work/viper/viper/modules/pe.py", line 1014, in run
    self.security()
  File "/home/user/work/viper/viper/modules/pe.py", line 643, in security
    cert_data = get_certificate(self.pe)
  File "/home/user/work/viper/viper/modules/pe.py", line 587, in get_certificate
    return pe.write()[address + 8:]
  File "/home/user/work/viper_archive/python2/venv/local/lib/python2.7/site-packages/pefile.py", line 2250, in write
    struct_data = bytearray(structure.__pack__())
  File "/home/user/work/viper_archive/python2/venv/local/lib/python2.7/site-packages/pefile.py", line 915, in __pack__
    return struct.pack(self.__format__, *new_values)
error: argument for 's' must be a string

Trace 'ascii' codec can't encode character u'\xa9' in position 10: ordinal not in range(128)
```

With `https://github.com/erocarrera/pefile/files/192316/pefile-2016.3.28.tar.gz#egg=pefile` it works:

```
viper 513a6e4e94369c64cab49324cd49c44137d2b66967bb6d16394ab145a8e32c45 > pe security
[*] Found certificate with MD5 e8fbb742e0d29f1ed5f587b3b769b426
```

**Comment by Rafiot** [comment]
My guess is that something somewhere should be bytes and is decoded.I'll try to fix it in the evening.

**Comment by frennkie** [comment]
Regarding the three RAT families that are not working (Hawkeye, PredatorPain and NJRat) I personally think those should not hold us back from merging this PR into master.
I tested a couple of Samples for exactly those RAT families and they were not detected in master.. so the according modules are most likely already a bit dated.
I would suggest moving them out into a separate branch were we can look into fixing (or discarding) them later.

**Comment by Rafiot** [comment]
I'm with you on that.

**Comment by Rafiot** [comment]
`pe signature` is now working on your sample \o/

**Comment by Rafiot** [comment]
Sooo we need to make sure androguard doesn't try to install ipython >=6.... 
https://travis-ci.org/Rafiot/viper/jobs/223733793#L601

**Comment by frennkie** [comment]
`pip --no-dependencies` could be a quick fix..

**Comment by Rafiot** [comment]
Yeah, but it will probably also break androguard

**Comment by Rafiot** [comment]
For the records, imphash generated was *wrong* on every pe sample that was relying on ordlookup in python3, the fix is there: https://github.com/viper-framework/pefile/commit/363de09734b55f3f52dfbb725ce90df4b659f53e

**Comment by Rafiot** [comment]
@frennkie @deralexxx last thing we need to do before merging: updating the documentation, because I already see the user coming to us "everything is broken", and they didn't use pip3 to install the modules.

**Pull request merged**
