### PR TITLE
Add note functions to API

### PR DESCRIPTION
**Pull request by kevthehermit**
View, Add, Update and Delete Notes. 

Takes the following POST Paramaters:

/file/notes/view
sha256:the file hash

/file/notes/add 
title:
body:
sha256

/file/notes/update
sha256:
body:
id:

/file/notes/delete
sha256:
id:

```
{
    "message": {
        "2": {
            "body": "Note two body",
            "title": "note 2 title"
        },
        "3": {
            "body": "Note three body",
            "title": "note 3 title"
        }
    }
}
```

### CODE REVIEW

**Comment by botherder** [comment]
The action filter should be a if/elseif switch then, no?

**Comment by deralexxx** [comment]
I will make some improvements on that and make a new pull request after

**Comment by deralexxx** [comment]
@kevthehermit I would close that pull request as I have already put it into the repo, hope that is okay for you

Thank you for the first shot of the notes API

**Comment by botherder** [comment]
Yep, this can be closed.

**Pull request closed without merging**
