### PR TITLE
[WIP] add module for fireeye sandbox

### PR DESCRIPTION
**Pull request by frennkie**
A colleague of mime implemented a module for the integration of Viper with the Fireeye Sandbox and we want to share this. 

I'm not yet entirely sure about the MISP part.. maybe @Rafiot could provide some guidance? :-D

Code also still needs a bit of polishing - therefore tagged as Work-In-Progress.

### CODE REVIEW

**Comment by frennkie** [comment]
@Rafiot Travis appears to have some issue.. the current default testing VM still seems to be Ubuntu 14.04 .. as support for Trusty is ending really soon I changed the dist to Xenial (16.04). This also required a change in the socksipy package name. 

For the last run Travis succeeded 2 of 4 and the two failures were not related to our code.. :-/

**Comment by Rafiot** [comment]
I restarted the runs on travis, it happens once in a while.

I'm a bit confused by the prints related to MISP: shouldn't it be using PyMISP directly instead?

**Comment by frennkie** [comment]
I wasn't sure how to best handle this... Currently this extracts relevant data from the result of the sandbox analysis... The Analyst should then use this to create (and maybe further enrich) the actual MISP event...

**Comment by botherder** [comment]
@frennkie Can you provide a rundown of the functionality this introduces? And what is the general purpose of this?

**Comment by frennkie** [comment]
@nex sure, will do... Is there a dedicated place to document individual modules (except for - - help)?

**Comment by botherder** [comment]
Not really, but I think if you summarize that here for us it would be good already.

**Comment by Rafiot** [comment]
@frennkie right, makes sense. I don't have a fireeye account, so I cannot look at the output in details, but it probably make sense to create full blown events, or at least objects from the output. I did something like that a while ago in the VT module: https://github.com/viper-framework/viper/blob/master/viper/modules/virustotal.py#L97

**Comment by botherder** [comment]
Closing this PR as modules are moved to https://github.com/viper-framework/viper-modules.

**Pull request closed without merging**
