### PR TITLE
Add Passive SSL module

### PR DESCRIPTION
**Pull request by Rafiot**
See: https://www.circl.lu/services/passive-ssl/

### CODE REVIEW

**Comment by Rafiot** [comment]
This one needs some more work.

**Comment by Rafiot** [comment]
The module is finished. 
The only part I'm not sure about is the fetching: it makes sense to be able to dump the pem file and to have all the possible information from a particular certificate but I'm unsure on the rendering in the console. Any idea?

**Comment by kevthehermit** [comment]
There is a merge conflict in there. 

For the fetch display you could use:

```

self.log('Info', 'Certificate Details')
self.log('item', ('Valid: {} -> {}\n'.format(cert_info['info']['not_before'], cert_info['info']['not_after']))
self.log('item', ('\t{}\n'.format(json.dumps(cert_info['info']['extension'], indent=2)))
self.log('item', ( '\tKey Length: {}\n'.format(cert_info['info']['keylength']))
self.log('item', ( '\tFingerprint: {}\n'.format(cert_info['info']['fingerprint']))
self.log('item', ( '\tIssuer: {}\n'.format(cert_info['info']['issuer']))
self.log('item', ( '\tSubject: {}\n'.format(cert_info['info']['subject']))
self.log('item', ( '\tKey: \n{}\n'.format(cert_info['info']['key']))
self.log('item', ( '\tPEM: \n{}\n'.format(cert_info['pem']))

```

which would output somethign like:

```
[+] Certificate Details
  [-] Valid: ...
  [-] Key Length: ..
```

**Comment by Rafiot** [comment]
Oh, nice, I'll do that, I didn't know it exists.

The merge conflict is probably the requirements file, I'll fix it asap.

**Comment by kevthehermit** [comment]
There are a couple of other options as well - 
https://viper-framework.readthedocs.org/en/latest/customize/index.html#printing-results

**Comment by Rafiot** [comment]
Great.

I fixed the merge issue and improed the rendering in the console.

**Comment by kevthehermit** [comment]
As always very nice and works well. Has a similar issue to pdns

Trailing / or a mistyped URL causes some issues

Sometimes it is handled nicley

```
viper > pssl -u xxxxxx -p xxxxxx --url https://www.circl.lu/v2pssl/ -f 47beabc922eae80e78783462a79f45c254fde68b
[!] Unable to decode JSON object: <html><title>404: Not Found</title><body>404: Not Found</body></html>
viper >

```

Sometimes not

```
viper > pssl -u xxxxxxx -p xxxxxxxx --url https://www.circl.lu/v2pssl/ -i 192.186.204.171
[!] The command pssl raised an exception:
Traceback (most recent call last):
  File "/root/github/viper/viper/core/ui/console.py", line 266, in start
    module.run()
  File "/root/github/viper/modules/pssl.py", line 102, in run
    self.query_ip(self.args.ip)
  File "/root/github/viper/modules/pssl.py", line 31, in query_ip
    result = self.pssl.query(ip)
  File "/usr/local/lib/python2.7/dist-packages/pypssl/api.py", line 58, in query
    return self._query(urljoin(self.base_url, path))
  File "/usr/local/lib/python2.7/dist-packages/pypssl/api.py", line 34, in _query
    raise Exception('Unable to decode JSON object: ' + response.text)
Exception: Unable to decode JSON object: <html><title>404: Not Found</title><body>404: Not Found</body></html>
viper > pssl -h

```

Also seems like i can give it made up URI's and it still works. 

```
viper > pssl -u xxxxx -p xxxxx --url https://www.circl.lu/gibberishrandomurl -i 216.58.208.46
[*] 216.58.208.46 :
 - bbdce13e9d537a5229915cb123c7aab0a855e798
 - --> C=US, O=Google Inc, CN=Google Internet Authority G2

 - 195057f8eefeaa31122a72cfb86081ad4c1c1d12
 - --> C=US, ST=California, L=Mountain View, O=Google Inc, CN=*.google.com

 - 490c7970478582d9bcbe8cc4e3203ad86c4829ff
 - --> C=US, ST=California, L=Mountain View, O=Google Inc, CN=*.google.com

 - f71517c5bc5b7b7fa73db075a7e6764b600849be
 - --> C=US, ST=California, L=Mountain View, O=Google Inc, CN=*.google.com


```

**Comment by Rafiot** [comment]
Oh, sorry for that, fixing it today...

**Pull request merged**
