### PR TITLE
[WIP] Add validation of the configuration file

### PR DESCRIPTION
**Pull request by frennkie**
Add a method to the Config class to validate the provided configuration file. The validation currently checks whether a given set of (statically defined) sections is present in the config file. 
The reason for this PR is that a lot of users most likely use a config file that is not in the git path (e.g. ~/.viper/viper.conf). When we add a feature that requires a new section then some users might not notice this and will never update their config file.

What do you guys think?

An alternative would be to "silently" edit/update the config file when a sections/variable is missing.

It would also be possible to use (some) defaults even if a section is missing. But this is currently not handled in most of the code base (e.g. if there is no `paths` section then `viper-cli` will crash).

This could also be extended to e.g. check for deprecated sections and print a warning or for optional settings (also with a warning).

### CODE REVIEW

**Comment by Rafiot** [comment]
What about a wrapper that prints a warning, but also grab the default value out of the sample config file?

**Comment by frennkie** [comment]
So the wrapper would first check whether all sections are present and then also whether all parameters within each sections are set (and set the defaults if not), right?

+1 because I think having this in a central location is better than having it distributed throughout the core and the modules.

**Comment by Rafiot** [comment]
Yep, sounds good to me.

**Comment by botherder** [comment]
@frennkie can you please review this and see if we should still merge it?

**Comment by frennkie** [comment]
Let me look into this again (it has been a while..)

**Comment by botherder** [comment]
@frennkie could you resolve conflict issues in this PR and merge it? Thanks!

**Comment by botherder** [comment]
I would actually suggest making the validation function return a bool value and let the console determine if and how to terminate.

**Comment by frennkie** [comment]
Sorry.. too many side projects. I'm closing this PR - anyone feel free to pick it up.

**Pull request closed without merging**
