### PR TITLE
Fix PEHash to match TotalHash Implementation

### PR DESCRIPTION
**Pull request by kevthehermit**
Fix the PEHash implementation as per https://github.com/viper-framework/viper/pull/218

This patch makes Viper PeHash match TotalHash as per https://totalhash.cymru.com/blog/pehash-source-code/

### CODE REVIEW

**Comment by nheijmans** [comment]
Thank you for this update. Appreciate it!

**Comment by AnyMaster** [comment]
Hi kevthehermit, 
Why do you want to implement pehash that  will  "match TotalHash Implementation" ?
Do you want match with completely wrong implementation?

https://gist.github.com/wxsBSD/07a5709fdcb59d346e9e

**Comment by elhoim** [comment]
A number of places have implemented the version from TotalHash, so the problem is that you have a widespread version that is wrong and a correct version.

Would there be a possibility of using/storing both and labelling the incorrect but widespread one with something like **pehash-incorrect** and the correct one as **pehash** ?

**Comment by nheijmans** [comment]
Is TotalHash been contacted about this issue? Because if they are spreading a wrong version maybe they should update the script and send an update post to everyone. This way we are all using one version instead of different ones, all claiming to be the right one. On the long run this will be more effective and efficient. Otherwise you cannot compare PEhashes with different products due to the different scripts that are being used.

**Comment by kevthehermit** [comment]
If anyone can give me a functional bit of code thst is actually correct I will use it. In the meantime its better to have something wrong but matches the rest of the research community. Otherwise everyone is wrong and the point of being able to use it to correlate or search is pointless and it may as well be removed.

**Comment by AnyMaster** [comment]
Looks like I have to implement "pehashng"
;)

**Comment by AnyMaster** [comment]
Hi,
Please have to look at https://github.com/AnyMaster/pehashng

**Pull request merged**
