### PR TITLE
Adding script view for non-binary files

### PR DESCRIPTION
**Pull request by lksnyder0**
Allows for storing and reading scripts in viper. It includes syntax highlighting for the most common languages.

### CODE REVIEW

**Comment by botherder** [comment]
@kevthehermit wanna look into this?

**Comment by kevthehermit** [comment]
Tested, Not many use cases but I kind of like it for looking at web shells and html pages i pull down. 

@lksnyder0 can you add a test to only load script files. If you try to load binary files it gets a bit upset. 

You could use something like 

if  __sessions__.current.file.mime in ['text/x-php', 'text/html', 'text']:

**Comment by Rafiot** [comment]
Is it still relevant now? I'm not sure what the status of the web interface is.

**Comment by deralexxx** [comment]
as we do not have a PR for the new web UI I would recommend to get this PR merged (but it has some conflicts, maybe @lksnyder0 can fix them - knowing this PR is quite old)

**Comment by botherder** [comment]
Closing for inactivity. Comment here if this needs to be revived and I will reopen.

**Pull request closed without merging**
