### PR TITLE
Update a MISP event via Viper (all fields)

### PR DESCRIPTION
**Pull request by Rafiot**
The code is getting bigger and I know you're going to hate that: it touches files in core, in order to save a MISP event in the session.

I'm not sure it is the best way to do it, but I think it is important to have the following:
* clearly mark in the console that we have a "MISP session" (event ID)
* being able to add attributes without having to pass the event ID as parameter all the time

I'll be happy to update this pull request accordingly if you have a better idea.

### CODE REVIEW

**Comment by Rafiot** [comment]
Something that would be nice: being able to interact with a misp event without having to open a session on a file (but just open a session "with a MISP event"). I'm not sure how to do that.

**Comment by Rafiot** [comment]
also, before you start playing around and nothing works, you need pymisp master for that module to work, I didn't create a tag for now

**Comment by kevthehermit** [comment]
Showing an active session makes sense. Maybe include MISP so ```Viper > Filename.exe [MISP 17]``` instead of ```viper > FileName.exe [17]```

I cant open a session on a MISP event unless i have a viper session on a file. 

```
viper > misp get_event 17
[!] No session opened
viper >

```

If i open any random file then i can. But this is confusing as the MISP session does not match the viper session

```
viper > open -l 648
[*] Session opened on /github/viper/binaries/7/b/a/0/7ba06c6a33763e9e97950289cb727779ac8107a99b8c93b31d8731bf97385e7b
viper pred_Sample.exe > misp get_event 17
viper pred_Sample.exe [17] > misp show
+--------+------------------------------------------------------------------+---------+
| type   | value                                                            | comment |
+--------+------------------------------------------------------------------+---------+
| md5    | e662e5ba993b61b3e2a6ba20e5181a68                                 |         |
| mutex  | \BaseNamedObjects\8113fad94fa6774baf2887e6c7290f02               |         |
| sha256 | 7d2257623b6c7ef4372d57e591d74c5630d2a812588bdc00178c5b271776fb85 |         |
| domain | 014.ignorelist.com                                               |         |
| domain | 014.gotdns.ch                                                    |         |
+--------+------------------------------------------------------------------+---------+
viper pred_Sample.exe [17] >

```

```
viper > open -l 4
[*] Session opened on /github/viper/binaries/0/c/e/8/0ce826f59270141457351ff85eb6a7cecd324d42cbb0c2f7550bca880718ffe3
viper DarkComet.exe > misp get_event 17
viper DarkComet.exe [17] > misp show
+--------+------------------------------------------------------------------+---------+
| type   | value                                                            | comment |
+--------+------------------------------------------------------------------+---------+
| md5    | e662e5ba993b61b3e2a6ba20e5181a68                                 |         |
| mutex  | \BaseNamedObjects\8113fad94fa6774baf2887e6c7290f02               |         |
| sha256 | 7d2257623b6c7ef4372d57e591d74c5630d2a812588bdc00178c5b271776fb85 |         |
| domain | 014.ignorelist.com                                               |         |
| domain | 014.gotdns.ch                                                    |         |
+--------+------------------------------------------------------------------+---------+
viper DarkComet.exe [17] >

```

**Comment by kevthehermit** [comment]
You can also make pip install master from git instead of pypip.

Not sure on the exact syntax but something similar to 
```
git+https://github.com/smarnach/pyexiftool.git#egg=pyexiftool
```
taken from the existing requirements.txt

**Comment by Rafiot** [comment]
1. It doesn't make much sense to require a viper session to be open on a file to open a misp event, but I didn't find an easy way to create a new session without providing a file (I didn't investigate much, doing it now).

2. Opening a viper session on a file from a MISP event would be very cool, but I'm not sure how much changes it is going to require (I don't know if it is possible to use 'find' from an other module for example).

3. I prefer to use the pypi version of the module because that way, I can make sure I really create a new release of the module and someone installing viper doesn't gets an half broken package because I pushed a bad commit without noticing.

**Comment by kevthehermit** [comment]
1 Will have a look see if i can find a nice way of doing this. Im thinking something like this. 

```
    def get_event(self):
        if __sessions__.is_set():
            self.log('warning', "Closing open session")
            __sessions__.close()
        else:
            # Open a session on a tmp file. - 
            __sessions__.new('/tmp/misp')

        event = self.misp.get_event(self.args.event)
        __sessions__.current.misp_event = MispEvent(event.json())
```


2 You can access the DB yourself.Some example code here

```
from viper.core.database import Database
from viper.core.session import __sessions__
from viper.core.storage import get_sample_path

            db = Database()
            rows = db.find(key=key, value=target)

            if not rows:
                self.log('warning', "No Matching Hash in Viper. Add using misp -- add command.")
                return

            path = get_sample_path(rows[0].sha256)
            if path:
                __sessions__.new(path)

```

3 Makes sense :)

**Comment by Rafiot** [comment]
A pretty big commit is getting there in a few min. It is going to solve 1 and 2 but also modifies a bit core :)

**Comment by kevthehermit** [comment]
Looking good. Found this error. 

```
viper > misp get_event 1
[*] Session opened on MISP event 1
[*] No known samples in that event.
viper  [MISP 1] > misp show
+-----------------+-----------------------------------------------------------------------------------------------------------------------------------+---------+
| type            | value                                                                                                                             | comment |
+-----------------+-----------------------------------------------------------------------------------------------------------------------------------+---------+
| filename|sha1   | 5aa004268b0bfa24a9f9b519d6ed99b67b427c7cc018fb5122e9915ceb69af5a|853e627d3a44b16bda97bf7d8b2047f720e4b734                         |         |
| filename|sha1   | 0ee942ae726add42603b29900144130c36ad3187ec7ab200b922307ed007603f|4191b376262abf90eb790115e0f65620f27e386c                         |         |
| filename|sha256 | 5aa004268b0bfa24a9f9b519d6ed99b67b427c7cc018fb5122e9915ceb69af5a|5aa004268b0bfa24a9f9b519d6ed99b67b427c7cc018fb5122e9915ceb69af5a |         |
| filename|sha256 | 0ee942ae726add42603b29900144130c36ad3187ec7ab200b922307ed007603f|0ee942ae726add42603b29900144130c36ad3187ec7ab200b922307ed007603f |         |
| malware-sample  | 5aa004268b0bfa24a9f9b519d6ed99b67b427c7cc018fb5122e9915ceb69af5a|595c235c600d374d9fe17c281cf5143a                                 |         |
| malware-sample  | 0ee942ae726add42603b29900144130c36ad3187ec7ab200b922307ed007603f|be4938b075c186cce420445219edad65                                 |         |
+-----------------+-----------------------------------------------------------------------------------------------------------------------------------+---------+
viper  [MISP 1] > misp download -e 1
[!] The command misp raised an exception:
Traceback (most recent call last):
  File "/root/github/viper/viper/core/ui/console.py", line 270, in start
    module.run()
  File "/root/github/viper/modules/misp.py", line 543, in run
    self.download()
  File "/root/github/viper/modules/misp.py", line 175, in download
    ok, data = self.misp.download_samples(event_id=self.args.event)
  File "build/bdist.linux-x86_64/egg/pymisp/api.py", line 548, in download_samples
    zipped = StringIO(base64.b64decode(f['base64']))
TypeError: initial_value must be unicode or None, not str
viper  [MISP 1] >

```

Using pymisp 1.8 did a pull and install from master.

**Comment by Rafiot** [comment]
Oh, thanks, fixed now (in v1.8.1) but I cannot push it on PyPi now, because I don't have the config on this computer... :) 

In the mean time:
```
pip install git+https://github.com/CIRCL/PyMISP.git@v1.8.1#egg=Package
```

**Comment by kevthehermit** [comment]
Nice thanks :)

Download works.

Sorry to be a pain. Some unhandled errors

```
viper  [MISP 1] > misp add hashes
[!] The command misp raised an exception:
Traceback (most recent call last):
  File "/root/github/viper/viper/core/ui/console.py", line 270, in start
    module.run()
  File "/root/github/viper/modules/misp.py", line 553, in run
    self.add()
  File "/root/github/viper/modules/misp.py", line 463, in add
    event = self.misp.add_hashes(current_event, filename=__sessions__.current.file.name,
AttributeError: 'NoneType' object has no attribute 'name'
viper  [MISP 1] >

```

Upload seems to be broken, Or i am using it incorrectly

With MISP Session

```
viper sample.doc [MISP 22] > misp upload -e 22
[!] The command misp raised an exception:
Traceback (most recent call last):
  File "/root/github/viper/viper/core/ui/console.py", line 270, in start
    module.run()
  File "/root/github/viper/modules/misp.py", line 539, in run
    self.upload()
  File "/root/github/viper/modules/misp.py", line 204, in upload
    ' '.join(self.args.info), self.args.analysis, self.args.threat)
TypeError
viper sample.doc [MISP 22] >

```

Without MISP session

```
viper sample.doc > misp upload -d 3 -ids -c 0 -a 2 -t 3
[!] The command misp raised an exception:
Traceback (most recent call last):
  File "/root/github/viper/viper/core/ui/console.py", line 270, in start
    module.run()
  File "/root/github/viper/modules/misp.py", line 539, in run
    self.upload()
  File "/root/github/viper/modules/misp.py", line 204, in upload
    ' '.join(self.args.info), self.args.analysis, self.args.threat)
TypeError
viper sample.doc >

```

**Comment by Rafiot** [comment]
No worries, I definitely didn't do enough tests :) 

Working on it.

**Comment by Rafiot** [comment]
And... fixed, until the next one :) 

Also: 
```
pip install git+https://github.com/CIRCL/PyMISP.git@v1.8.2#egg=Package
```

**Comment by kevthehermit** [comment]
Found my next one :)

```
viper Minecraft.exe [MISP 23] > misp add hashes
[!] {u'url': u'/events/23', u'message': u'Event could not be saved: No timestamp on the pushed edit or event in the request not newer than the local copy.', u'name': u'Event could not be saved: No timestamp on the pushed edit or event in the request not newer than the local copy.'}
viper Minecraft.exe [MISP 23] >

```

Is there a way to refresh the MISP session. After upload it doesnt show any attributes until i open the misp session again

```
viper Minecraft.exe > misp create_event -d 3 -ids -i 'DarkComet - b479e6f6dfd695c996dc275ba19c35dc' -a 1 -t 2
[*] Session opened on MISP event 23
[*] This event contains 0 samples.
[*] No known (in Viper) samples in that event.
viper Minecraft.exe [MISP 23] > misp upload
[+] File uploaded sucessfully
viper Minecraft.exe [MISP 23] > misp show
+------+-------+---------+
| type | value | comment |
+------+-------+---------+
+------+-------+---------+
viper Minecraft.exe [MISP 23] > misp get_event 23
[*] Session opened on /root/github/viper/binaries/0/c/f/7/0cf7270dc2bc92351dd80510b7ee0e0b44d18aa0fb9ca3c5ea44a9e28e8ccd58
[*] Session opened on MISP event 23
[*] This event contains 1 samples.
viper Minecraft.exe [MISP 23] > misp show
+-----------------+--------------------------------------------------------------------------------+---------+
| type            | value                                                                          | comment |
+-----------------+--------------------------------------------------------------------------------+---------+
| filename|sha1   | Minecraft.exe|3201a2f6c9d94d083171a6840f02ccb2b3c2d102                         |         |
| filename|sha256 | Minecraft.exe|0cf7270dc2bc92351dd80510b7ee0e0b44d18aa0fb9ca3c5ea44a9e28e8ccd58 |         |
| malware-sample  | Minecraft.exe|b479e6f6dfd695c996dc275ba19c35dc                                 |         |
+-----------------+--------------------------------------------------------------------------------+---------+
viper Minecraft.exe [MISP 23] >

```

**Comment by Rafiot** [comment]
For the first issue, did you update your MISP instance? I think it is resolved by that commit: https://github.com/MISP/MISP/commit/e7b54c2c6131a7ab7806bb12c0293057007d0d39

For the second one, it is a bit more complicated: the API to upload a sample doesn't return the Event ID (https://github.com/MISP/MISP/issues/654). But in your case, it doesn't matter as you are already in a MISP session. Fixing it :)

**Comment by kevthehermit** [comment]
Refresh works great :)

Updated my MISP to:
Currently installed version..... v2.3.125	
Latest available version..... v2.3.125	
Status..... OK

Now i get this 

```
viper > misp get_event 23
[*] Session opened on /root/github/viper/binaries/0/c/f/7/0cf7270dc2bc92351dd80510b7ee0e0b44d18aa0fb9ca3c5ea44a9e28e8ccd58
[*] Session opened on MISP event 23.
[*] This event contains 1 samples.
viper Minecraft.exe [MISP 23] > misp add hashes
[!] {u'message': u'Error'}
viper Minecraft.exe [MISP 23] >

```

**Comment by Rafiot** [comment]
My guess is that you try to re-add existing attributes and MISP in unhappy about it... I'll give a try later and open an issue on MISP side in that case so we have a better error message.

**Comment by kevthehermit** [comment]
Yeah that makes sense. 

If i create a new event, add hashes then upload it all works fine. Its only if i upload then try to add hashes it gets upset. 

Will run a couple more tests then if nothing else pops up will merge tonight. Thanks again for all your work on this.

**Comment by Rafiot** [comment]
Yep, I tried again too and it is in fact a bug in MISP => https://github.com/MISP/MISP/issues/655

Cool, thank you, and let me know if you find any other issue :)

**Pull request merged**
