### PR TITLE
Add autorun to the api

### PR DESCRIPTION
**Pull request by trolldbois**

### CODE REVIEW

**Comment by Rafiot** [comment]
Is it really something we want by default in the API? I'm not sure.

**Comment by neriberto** [comment]
I miss this feature!

**Comment by Rafiot** [comment]
should it be a parameter then? 

@neriberto do you mind doing a PR with that feature? I'll merge it immediately (this one has a conflict)

**Comment by neriberto** [comment]
@Rafiot I need get finished all my ideas about clamav first then I will do a pull request about it.

I need something that when receive a file through API start a scan with clamav and other modules, so I can priorize what look first... then (to me) implement the autorun in API is very cool...

**Comment by Rafiot** [comment]
Of course, no rush, I just want to cleanup the current PR/issues

**Comment by 2sec4u** [comment]
This would be really useful as a parameter, would you also be able to add it to the new `/file/add_url` API endpoint?

**Comment by botherder** [comment]
Closing for inactivity. Comment here if this needs to be revived and I will reopen.

**Pull request closed without merging**
