### PR TITLE
Cleanup Radare2 module

### LINKED ISSUE #354: Display problem using radare2 within the viper
I'm encountering a display issue using @radare within the viper. The visual mode isn't responsive, and when quitting it's doing weird stuff see this asciinema: http://radare.tv/a/103

### PR DESCRIPTION
**Pull request by Rafiot**
Fix #354 

The module was full of useless code (r2 can open any file and doesn't need all the checks of the ida module)

### CODE REVIEW

**Comment by Rafiot** [comment]
Don't merge, while I'm at it, I'm adding initial support to r2pipe (#235)

**Comment by Rafiot** [comment]
There is a basic support now, and it will be presented  during the radare2 workshop at hack.lu. Any chance you can merge it tomorrow? I don't thing anyone was using this module before anyway.

**Comment by botherder** [comment]
"17 additions and 57 deletions" these are the commits I like. Sorry, I didn't manage to merge in time. Doing it now.

**Comment by Rafiot** [comment]
Hehe :) I love removing code.

Also, it is totally fine, the radare2 workshop is this Tuesday. Thank you or merging! cc @maijin

**Comment by Maijin** [comment]
:+1: Yep I've seen thank you very much mate :smile_cat:

**Pull request merged**
