### PR TITLE
Update Androguard version and URL

### PR DESCRIPTION
**Pull request by 2xyo**
Latest version of Androguard is 2.0 on Github.

### CODE REVIEW

**Comment by botherder** [comment]
Androguard is also on Pypi, shall we just add it to the requirements.txt file?

**Comment by 2xyo** [comment]
Yes you can and it's a better solution.

However, I don't know if the Pypi repo is official as it is maintained by @jbremer.

Note:  the latest stable release is tagged v2.0 (androguard/androguard@ff828c318824d62d98977bcb20b4ecebe8827a62) but the [setup.py](https://github.com/androguard/androguard/blob/ff828c318824d62d98977bcb20b4ecebe8827a62/setup.py) version is 3.0.

**Comment by botherder** [comment]
If upstream as a valid setuptools script, we can just add it to requirements.txt as a git+ entry.

**Comment by 2xyo** [comment]
viper doesn't work with the master branch of `androguard` as `ganalysis` has been removed from `androguard.core.analysis`.

**Comment by botherder** [comment]
Ah, that sucks.

**Comment by kevthehermit** [comment]
I will look at it tonight

**Pull request merged**
