### PR TITLE
add basic logging

### PR DESCRIPTION
**Pull request by frennkie**
While working on the py3 and django branch I found it pretty useful to have some file logging (including a debug switch).

### CODE REVIEW

**Comment by Rafiot** [comment]
It would be better to put the logfile in viper home directory by default (obviously, you can overwrite it)

**Comment by frennkie** [comment]
The result of this change is that viper-cli has two new command line options:

```
usage: viper-cli [-h] [-p PROJECT] [--log LOG] [-d]

optional arguments:
  -h, --help            show this help message and exit
  -p PROJECT, --project PROJECT
                        Specify a new or existing project name
  --log LOG             Logfile (default: ~/.viper/viper.log)
  -d, --debug           Enable debugging
```

A regular log line (`log.info("foo")`) looks like this:
```
2017-03-26 12:54:23,899 - viper - INFO - Starting viper-cli
```

Enabling `--debug` will also print `DEBUG` messages and will include the file and line of the log statement: 
```
2017-03-26 12:54:47,319 - viper - console.py:102 - INFO - Starting viper-cli
```

**Comment by Rafiot** [comment]
I looked a bit more at how the base path is set globally in a viper session, and it is done in the Project: https://github.com/viper-framework/viper/blob/master/viper/core/project.py#L11

And it seems to me it will be cleaner to have the logging also configured there. What do you think?

**Comment by frennkie** [comment]
Interessting.. I think I agree.. setting up the logger in project seems cleaner. 

Before I do any changes:
* This would then mean that there is no user input possibility yet - which I don't think is bad. So I would drop the --log CLI setting and we just always log to the base_path, sounds ok?
* How about the debug switch?
* Or should I simply add both directives to the viper.conf?

**Comment by Rafiot** [comment]
* always logging in the base_path sounds good to me. What do you think about adding a command to show/clean the log from the CLI? 
* Yeah, let's add the debug switch in the config file, I think it is better.

**Comment by frennkie** [comment]
After the suggested changes this PR now configures logging based on a new section in the Viper config file.
The section has two settings and is called: **[logging]**

* **log_file**: string
   log file (full path - e.g. */tmp/viper.log*)
   If left blank, the default will be *$storage_path/viper.log*
* **debug**: True or False
   enable additional debug logging

**Comment by deralexxx** [comment]
Looks okay for me

**Comment by Rafiot** [comment]
Same, merging then :)

**Pull request merged**
