### PR TITLE
Improved Androguard speed processing using current session to cache

### PR DESCRIPTION
**Pull request by plutec**
I use current session to store androguard values and not calculating every time apk module is loaded, only the first time in the session.

### CODE REVIEW

**Comment by plutec** [comment]
Travis CI fail:
 
Could not find a version that satisfies the requirement bitstring==3.1.3 (from -r requirements.txt (line 4)) (from versions: 0.3.2, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.5.1, 0.5.2, 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.2.0, 1.3.0, 2.0.0b1, 2.0.1b2, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.2.0, 3.0.0, 3.0.1, 3.0.2, 3.1.0, 3.1.1, 3.1.2, 3.1.4)
 No distributions matching the version for bitstring==3.1.3 (from -r requirements.txt (line 4))

**Comment by Rafiot** [comment]
bitstring issue fixed there: https://github.com/viper-framework/viper/pull/428

**Comment by plutec** [comment]
Thanks @Rafiot

**Comment by plutec** [comment]
Merged fix #428

**Pull request merged**
