### PR TITLE
[WIP] Improve completion

### LINKED ISSUE #515: bash-completion/Cisco-like CLI
I often wonder if it is time to allow us to hit "TAB" key for auto-completion of keystrokes.

And that includes the dash options as well.  <<- emphasis

Perhaps, Python Fire module can help us out here.

https://github.com/google/python-fire

### PR DESCRIPTION
**Pull request by frennkie**
I looked into improving the (tab/auto) completion in the viper-cli.

For the modules I was able to write two custom introspection functions that find out which argparse options a `Module` uses (I wasn't able to find an "official" way to get a list of arguments that argparse works with - if anybody has any hints.. highly welcome).

~Unfortunately the commands are methods and not classes themselves (as with the modules) - therefore the same approach doesn't work there.~

I changed the commands to also be subclasses of a new `Command` class and was then able to do almost the same introspection as with the modules.

The completion is now able to complete commands (and then the specific options for each command), modules (with options), modules with additional commands (subparser, also with options) and - where it makes sense - the path to a file/folder on disk.

Showcase:

```
$: ./viper-cli
         _
        (_)
   _   _ _ ____  _____  ____
  | | | | |  _ \| ___ |/ ___)
   \ V /| | |_| | ____| |
    \_/ |_|  __/|_____)_| v1.3-dev
          |_|

You have 29 files in your default repository
viper > misp<tab><tab>
--help        --off         --url         add           check_hashes  download      publish       search        store         upload        yara
--key         --on          --verify      add_hashes    create_event  open          pull          show          tag           version
viper > misp t<tab><tab>
viper > misp tag --<tab><tab>
--attribute  --details    --event      --help       --list       --search
viper > misp tag --event --<tab><tab>
--attribute  --details    --help       --list       --search
```

@Rafiot: Any idea how to do something similar with the commands? One option would be to also convert each command method into a separate class and then use the same code for introspection.

I think this would resolve / fix #515.

### CODE REVIEW

**Comment by frennkie** [comment]
Now also command and their arguments work.

**Comment by frennkie** [comment]
Local

**Comment by Rafiot** [comment]
Looks good to me, should I merge it now?

**Comment by frennkie** [comment]
Yepp, if it's also working for you and you don't see anything to improve.. then go ahead. :-)

**Comment by Rafiot** [comment]
:+1:

**Pull request merged**
