### PR TITLE
New string types in strings module

### PR DESCRIPTION
**Pull request by cvandeplas**
This pull request adds new string types for the strings module.
Additional extractions are:
- -N  for network related strings like URLs, user-agents, email addresses, 
- -I   for interesting strings like PDB, regkeys
- -F  for filenames

This latest commit also improves the string detection algorithm and adds support for ascii strings in wide format

### CODE REVIEW

**Comment by botherder** [comment]
This is good. Unfortunately I didn't see this before, and I had to do some tiny changes to the strings module yesterday. Would you mind porting your changes to the current master and update this pull request?

**Comment by cvandeplas** [comment]
I've just merged the changes.
I'm not completely happy with the way the `run()` function is done as there is a lot of redundancy with the extractions. 
However considering you've added the `# TODO: this function needs to be refactored.` and I don't have much time, I guess it will be for later.

**Comment by botherder** [comment]
Agreed.

**Comment by cvandeplas** [comment]
I finally cleaned up the run() function. 
I guess the code should be OK for merging now.

**Pull request merged**
