### PR TITLE
Added 'ls' command and opening files by id

### PR DESCRIPTION
**Pull request by vadimkotov**
ls - allows you to list all the samples, it should be faster than 'find all' as it doesn't loop through the rows, but renders the table directly from the SQL rows.The point of this command is to view all the files stored including the file id. As a result I had  to also implement opening files by id. For people mostly working in console it should be  easier than copy-pasting hashes. 
If needed I can re-do this pull and split it into several simpler requests as I know many people hate several features in one request.

### CODE REVIEW

**Comment by botherder** [comment]
There is one additional feature to this pull request, which is specifying the ID to the open command. Regarding the "ls", I'm not sure. It seems a bit redundant.

**Comment by vadimkotov** [comment]
Truth is I didn't realize there was 'find all' until after I've implemented 'ls', so it is kind of redundant :)  anyways, I can submit another request (and close this one) with the open by id feature, but in this case I'll have to tweak the output of find. How about that?

**Comment by botherder** [comment]
Hmm, ye we need to think about that, to avoid confusion with the results counter.
Can you elaborate what's the value of open --id?

**Comment by vadimkotov** [comment]
Again, I might be missing something, but I noticed that you can open a _previously stored_ file only by its hash value. It seems to me as a bit of a hassle because you need to Ctrl+C Ctrl-V the hash value of the sample. I thought it might be a little bit more efficient if you could provide the file ID instead, because this is a console application and I'd like to avoid using mouse for copy-pasting. This is of course very subjective - I don't claim it's a super useful feature, it just suits my style of work better so I thought I'd share if somebody else needed it :) 
Is there a better way to open the stored files that has been already implemented? I might have just missed it :(
Thanks for looking into the pull request :)

**Comment by botherder** [comment]
Actually, you can also open files by doing something like:

```
viper > find all
+---+---------------------+-----------------------+----------------------------------+------+
| # | Name                | Mime                  | MD5                              | Tags |
+---+---------------------+-----------------------+----------------------------------+------+
| 1 | kelihos.exe         | application/x-dosexec | e15e7d8f793aaaae40947e92cb57642b |      |
| 2 | kelihos_recent2.exe | application/x-dosexec | bef5752a9159a169bc554b862435e07d |      |
| 3 | kelihos_recent.exe  | application/x-dosexec | c0d1c2988c244ddb98505bbf2ba451e9 |      |
+---+---------------------+-----------------------+----------------------------------+------+
viper > open --last 1
[*] Session opened on /home/nex/.viper/binaries/6/a/e/c/6aec74fb27b315fa04fc3621e0f4f858e68c2fe1d27724bd0514093b8ba2f703
viper kelihos.exe >
``` 

In this case, it isn't properly the ID with which the file is stored in the database, but the Viper sessions maintains a list of all the entries from the results of the last `find` command, and with `open --last 1` you open the first entry from such results.

**Pull request closed without merging**
