### PR TITLE
Add URL parser for apk module

### PR DESCRIPTION
**Pull request by 18z**
Hi, 

I tried to use string module to obtain url from the android apk but the result is not good.
So I enforce the apk module to parse url.

I hope this is helpful. :smile:

### CODE REVIEW

**Comment by frennkie** [comment]
Looks okay to me. I added a unittest in the (still pending) py3_apk branch: https://github.com/Rafiot/viper/pull/11/files

**Comment by 18z** [comment]
@frennkie thanks for adding a unitest in the py3_apk branch. 
The PR is still not merged, anything missed? : )

**Comment by Rafiot** [comment]
I was traveling without a laptop, merging now :)

**Comment by 18z** [comment]
Thanks : )

**Pull request merged**
