### PR TITLE
Added size command

### PR DESCRIPTION
**Pull request by emdel**
I added the 'size' command that I find useful for some daily activities and some minor modifications.

### CODE REVIEW

**Comment by deralexxx** [comment]
needs to be tested, but looks fine for me

**Comment by emdel** [comment]
I added the 'size' command also to the ELF module.
Have a look at: https://github.com/viper-framework/viper/pull/426/commits/5ad72e50561eb42eb97b6863b60af195194680b3

**Comment by botherder** [comment]
Would be better as a standalone module. Good work, keep it up.

**Comment by emdel** [comment]
OK. I will create a new PR asap.

**Pull request closed without merging**
