### PR TITLE
Add Passive DNS module

### PR DESCRIPTION
**Pull request by Rafiot**
See: https://www.circl.lu/services/passive-dns/

### CODE REVIEW

**Comment by kevthehermit** [comment]
Requesting access to Passive-DNS and Passive-SSL so i can test and merge

**Comment by Rafiot** [comment]
Can you send a mail to info@circl.lu, please?

**Comment by kevthehermit** [comment]
Am already in the queue i think. [circl.lu #175737]

**Comment by Rafiot** [comment]
Woops, you should have a mail with the credentials now :)

**Comment by kevthehermit** [comment]
Thanks :) Will test and merge tomorrow.

**Comment by kevthehermit** [comment]
Awesome work :)

Couple of things I noticed.

Needs error handling for bad authentication

```
viper > pdns -u username -p password -q circl.lu       
[!] The command pdns raised an exception:
Traceback (most recent call last):
  File "/root/github/viper/viper/core/ui/console.py", line 266, in start
    module.run()
  File "/root/github/viper/modules/pdns.py", line 48, in run
    data = pdns.query(self.args.query)
  File "/usr/local/lib/python2.7/dist-packages/pypdns/api.py", line 42, in query
    raise Exception('HTTP error authentication incorrect?')
Exception: HTTP error authentication incorrect?
viper > 

```

The help for -q QUERY says "Password on the PDNS instance"

If you leave the trailing / on the URL it always comes back "unable to find"

```
viper > pdns --url https://www.circl.lu/pdns/query -q 192.186.204.171
[+] 2015/08/03 07:44 -> 2015/08/10 12:13 (2 requests)
	 RR Name: chip-dfir.techanarchy.net - Data: 192.186.204.171
[+] 2015/03/13 09:17 -> 2015/08/25 02:59 (14 requests)
	 RR Name: techanarchy.net - Data: 192.186.204.171
[+] 2015/03/13 09:17 -> 2015/09/02 09:17 (25 requests)
	 RR Name: techanarchy.net - Data: ns20.domaincontrol.com
[+] 2015/03/13 09:17 -> 2015/09/02 09:17 (25 requests)
	 RR Name: techanarchy.net - Data: ns19.domaincontrol.com
viper > pdns --url https://www.circl.lu/pdns/query/ -q 192.186.204.171
[!] Unable to find 192.186.204.171.
viper > 

```

**Comment by Rafiot** [comment]
Thank you for the feedbacks, I'll push an update :)

**Comment by Rafiot** [comment]
Done :)

**Pull request merged**
