### PR TITLE
PHP similarity files

### PR DESCRIPTION
**Pull request by Kalliades**
Hi guys,

I've been working on some similarity analysis stuff as part of my research, specifically for PHP-based shells. The modules I've added allow you to do some code normalisation and comparisons, and to visualise the results using heatmaps or dendrograms. The goal is to find relationships between shells, and to determine whether normalisation increases the observed levels of similarity. 

I thought I'd put some of the work I've done on GitHub for you to have a look at, and if you'd like you could possibly incorporate it into a new branch.

### CODE REVIEW

**Comment by deralexxx** [comment]
hm that is quite a lot of new modules, can you somehow merge that into one big php module?

e.g. "functions" as a module is IMO not that self explaining as it mostly targets php specific files

**Comment by Kalliades** [comment]
That's a good idea, and I think it would make incorporating the functionality into Viper's master copy much neater. If I have some time in between writing up I'll merge all of the PHP stuff, in the meantime maybe a new PHP specific branch would be best? Thanks for the feedback

**Comment by botherder** [comment]
Yes, containing all in one module would be preferable. At this point your pull request already yields merge conflicts. If you can refactor it to be less impactful on the codebase, it'd be appreciated.

**Comment by kevthehermit** [comment]
@Kalliades can you do anything with this?

**Comment by Rafiot** [comment]
I have no idea what do to with this PR. 

@Kalliades are you still using it? doe sthis PR contains the most recent version of your code?

**Comment by deralexxx** [comment]
I would suggest to not merge that PR, but keep it open and we can create a new issue with "Come up with a php module" and then link the issue to that PR and we can slowly start implement parts of this PR.

Does that make sense?

**Comment by Rafiot** [comment]
Yep, makes sense.

**Comment by botherder** [comment]
Closing for inactivity. Comment here if this needs to be revived and I will reopen.

**Pull request closed without merging**
