### PR TITLE
Adding scan for virustotal module

### PR DESCRIPTION
**Pull request by dukebarman**
I modified virustotal module and add a few options:
--scan - scan all samples from repository and output status (you can submit samples to VS)
--engine - additional option for scan. Output signature for chosen antivirus engine
--resubmit - reanalyse sample

Scan:
scan_files

Scan with submit:
submit

### CODE REVIEW

**Comment by botherder** [comment]
There are some merge conflicts. Can you update your changes to the latest version of Viper? I'm shooting to merge this in 1.3.

**Comment by dukebarman** [comment]
No problem. I'm in business trip now so I can update it at next week

**Comment by GelosSnake** [comment]
Is it not better to change the --scan to --scanAll or something more indicative ?
Some people might get confused and submit unwanted private files to VT by mistake.

**Comment by botherder** [comment]
Anyone wants to take up on this?

**Comment by deralexxx** [comment]
I will try to repair it...

**Comment by Rafiot** [comment]
Anyone willing to update this PR?

**Comment by deralexxx** [comment]
still assigned to me, so will dedicate some time to it, but earliest would be next Monday

**Comment by botherder** [comment]
Closing for inactivity. Comment here if this is revived and I will reopen.

**Pull request closed without merging**
