### PR TITLE
Lief module integration

### PR DESCRIPTION
**Pull request by dusby**
Lief API integration in a module able to extract information from ELF, PE, Mach-O, OAT, DEX, VDEX and ART formats.
It is a huge module, lief -h and lief elf|pe|macho|oat|dex|vdex|art -h for more information.
Lief website : https://lief.quarkslab.com/
Lief repo : https://github.com/lief-project/LIEF
This should close issue #693

### CODE REVIEW

**Comment by dusby** [comment]
It seems that this pull request has to be merged first : https://github.com/viper-framework/viper-test-files/pull/6
Got some problems with submodules..... I think it is ok but not completely sure...

**Comment by botherder** [comment]
Thanks for this massive pull request.

It seems to me that this PR already includes the same test files as https://github.com/viper-framework/viper-test-files/pull/6. I'm slightly confused what's the appropriate place. @Rafiot, I believe you created viper-test-files. Can you clarify?

**Comment by dusby** [comment]
I was also confused regarding those test files as it is a submodule.

**Comment by Rafiot** [comment]
@botherder I'll look at the PR, not sure about the current status, it is definitely not ready to merge as-is.

@dusby Thank you for it, I'll get back to you with some feedback as soon as possible.

**Comment by Rafiot** [comment]
The PR look pretty good to me.

A few remarks:
* I did some reformatting on the code to make pep8 happy (spaces, stuff like that)
* You're using one-liners that are too long, and I'm probably going to rewrite them later. It works, but it super hard to understand and that's generally a bad idea
* I moved the sample.elf to the sub directory and added a few tests related to it.

**Comment by dusby** [comment]
Great !

It's noted for long lines, I will handle it, do not bother :-)

**Pull request merged**
